### ISSUE TITLE
Question : Can I limit the output of the sequence

### ISSUE THREAD

**Issue by ghost** [emil0r/ez-web#1]
Hello, 

I like to use your plugin for a project I use where a lot of pages are used. 
I have only 1 question. 

When I do :  (paginate (range 1070) 10 80) 

I see this output : 

:prev-seq (79 
            78 
            77 
            76 
            75 
            74 
            73 
            72 
            71 
            70 
            69 
            68 
            67 
            66 
            65 
            64 
            63 
            62 
            61 
            60 
            59 
            58 
            57 
            56 
            55 
            54 
            53 
            52 
            51 
            50 
            49 
            48 
            47 
            46 
            45 
            44 
            43 
            42 
            41 
            40 
            39 
            38 
            37 
            36 
            35 
            34 
            33 
            32 
            31 
            30 
            29 
            28 
            27 
            26 
            25 
            24 
            23 
            22 
            21 
            20 
            19 
            18 
            17 
            16 
            15 
            14 
            13 
            12 
            11 
            10 
            9 
            8 
            7 
            6 
            5 
            4 
            3 
            2 
            1), 
 :page 80, 
 :pages 107, 
 :next 81, 
 :prev 79, 
 :next-seq (81 
            82 
            83 
            84 
            85 
            86 
            87 
            88 
            89 
            90 
            91 
            92 
            93 
            94 
            95 
            96 
            97 
            98 
            99 
            100 
            101 
            102 
            103 
            104 
            105 
            106 
            107)} 

Is it possible to tell that I only want let's say 10 numbers of each seq 

Roelof

**Comment by emil0r** [comment]
Try this:

```clojure
(let [paginated (paginate (range 1070) 10 80)
        prev-seq (take 10 (:prev-seq paginated))
        next-seq (take 10 (:next-seq paginated))]
  {:prev-seq prev-seq
   :next-seq next-seq})
```

If you need to reuse it you could wrap it in a utility function. I'll take a closer look at extending the function with optional parameters for limiting the sequences.

**Comment by ghost** [comment]
Thanks, I will try it. Then I hope I can turn the outcome into a bootstrap template with Selmer  like this: 

     <ul class="pagination">
       <li><a href="#">1</a></li>
      <li><a href="#">2</a></li>
      <li><a href="#">3</a></li>
      <li><a href="#">4</a></li>
      <li><a href="#">5</a></li>
    </ul>
